// Nexus — ESLint flat config (ESLint 9). There is deliberately no .eslintrc* in this
// repo: one ESLint major, one config format.
//
// Formatting is Prettier's job and Prettier's alone — `eslint-config-prettier` is
// applied last so the two can never disagree about a comma.
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    // frontend/wailsjs is GENERATED by the wails CLI and committed so that the
    // typecheck gate can run without a full wails build; it is never hand-edited,
    // so it is never linted. frontend/dist is build output.
    ignores: ['dist/**', 'wailsjs/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  reactHooks.configs.flat['recommended-latest'],
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: { 'react-refresh': reactRefresh },
    rules: {
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // `npm run lint` runs with --max-warnings=0, so this genuinely fails the gate.
      // The leading-underscore escape hatch is for deliberately ignored arguments.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Build tooling runs in Node, not the browser.
    files: ['*.config.{js,ts}'],
    languageOptions: { globals: globals.node },
  },
  prettier,
);
