package main

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// The generated TypeScript client is part of the contract, and this file reads
// it (S2-02).
//
// # Why a test reads a generated file
//
// Every other wire test in this project asserts what GO does. They all passed
// while frontend/wailsjs/go/models.ts described `due` as a class with Year,
// Month and Day — a shape the wire has never carried — because Wails builds
// that file by reflecting over the structs and cannot see a MarshalJSON method.
// The Go side was right and the generated side was wrong, and nothing failed,
// because nobody opened the generated file. This is the test that opens it.
//
// The frontend is allowed to trust these types completely: PLAN.md §1 says the
// UI computes nothing, so a wrong type there is not a type error, it is a wrong
// number on a card. That is worth a test that reads the artifact.
//
// # It is checked in, so this is a real gate
//
// frontend/wailsjs/ is tracked. `make test` (gate 1) runs before
// `wails build` (gate 5), so if a DTO changes and the client is not regenerated,
// this test fails FIRST and says so — which is the intended order: the fix is
// `make build` and one more commit, not a stale client on main.

// wailsJSDir is where the Wails CLI writes the generated client.
const wailsJSDir = "frontend/wailsjs/go"

// tsClass is one generated class: its fully qualified name and the field
// declarations before the generated constructor.
type tsClass struct {
	name   string            // "domain.Node"
	fields map[string]string // "due" -> "due?: string"
	order  []string
}

var (
	tsNamespaceRe = regexp.MustCompile(`^export namespace (\w+) \{`)
	tsClassRe     = regexp.MustCompile(`^\s*export class (\w+) \{`)
	tsFieldRe     = regexp.MustCompile(`^\s*([A-Za-z_]\w*)(\??): (.+);$`)
	tsRefRe       = regexp.MustCompile(`\b(domain|service)\.(\w+)`)
)

// parseModels reads models.ts into the classes it declares. It is deliberately
// a dumb line scanner: a real TypeScript parser would be a dependency, and the
// generator's output is machine-written and uniform.
func parseModels(t *testing.T, src string) map[string]tsClass {
	t.Helper()

	classes := map[string]tsClass{}
	namespace := ""
	var current *tsClass

	for _, line := range strings.Split(src, "\n") {
		if m := tsNamespaceRe.FindStringSubmatch(line); m != nil {
			namespace = m[1]
			continue
		}
		if m := tsClassRe.FindStringSubmatch(line); m != nil {
			if namespace == "" {
				t.Fatalf("class %s is declared outside any namespace", m[1])
			}
			current = &tsClass{name: namespace + "." + m[1], fields: map[string]string{}}
			classes[current.name] = *current
			continue
		}
		if current == nil {
			continue
		}
		// The field block ends at the generated members; everything after is
		// plumbing (createFrom, the constructor, convertValues).
		if strings.Contains(line, "static createFrom") || strings.Contains(line, "constructor(") {
			current = nil
			continue
		}
		if m := tsFieldRe.FindStringSubmatch(line); m != nil {
			decl := strings.TrimSuffix(strings.TrimSpace(line), ";")
			c := classes[current.name]
			c.fields[m[1]] = decl
			c.order = append(c.order, m[1])
			classes[current.name] = c
		}
	}
	return classes
}

func readGenerated(t *testing.T, name string) string {
	t.Helper()

	data, err := os.ReadFile(filepath.Join(wailsJSDir, name))
	if err != nil {
		t.Fatalf("reading the generated %s: %v\n"+
			"It is checked in and is regenerated by `make build` (gate 5).", name, err)
	}
	return string(data)
}

// Every field that carries a date or an instant is typed as the string it is,
// and the two INPUT classes are on the same lowerCamelCase contract as the
// reads (S2-02).
//
// The expectations are written out in full rather than derived from Go by
// reflection, on purpose: deriving them would re-implement the generator's own
// mapping, and a test that agrees with the thing it is checking because it
// reasons the same way is not a check. These are the lines a human should read.
func TestGeneratedModelsMatchTheWire(t *testing.T) {
	classes := parseModels(t, readGenerated(t, "models.ts"))

	// The fields whose Go shape and JSON shape differ. Before S2-02's fix these
	// read `due?: Date` and `createdAt: any`.
	want := map[string]map[string]string{
		"domain.Node": {
			"due":         "due?: string",
			"createdAt":   "createdAt: string",
			"updatedAt":   "updatedAt: string",
			"completedAt": "completedAt?: string",
			"archivedAt":  "archivedAt?: string",
		},
		"service.TimerView": {
			"startedAt": "startedAt?: string",
		},
		// The create input, which had no json tags at all and generated
		// PascalCase field names and `Due?: domain.Date` — an object Go's
		// domain.Date.UnmarshalJSON refuses, so a create built from the
		// generated type could never have succeeded.
		"service.NewNode": {
			"parentId":      "parentId?: string",
			"type":          "type: string",
			"title":         "title: string",
			"descriptionMd": "descriptionMd: string",
			"status":        "status: string",
			"due":           "due?: string",
			"priority":      "priority: number",
			"estimateMin":   "estimateMin?: number",
			"recurrence":    "recurrence?: string",
			"activity":      "activity?: string",
		},
		// The search input, likewise.
		"service.SearchOptions": {
			"includeArchived": "includeArchived: boolean",
			"limit":           "limit: number",
		},
	}

	for className, fields := range want {
		t.Run(className, func(t *testing.T) {
			class, ok := classes[className]
			if !ok {
				t.Fatalf("models.ts declares no %s; it declares %v", className, classNames(classes))
			}
			for field, decl := range fields {
				got, ok := class.fields[field]
				if !ok {
					t.Errorf("%s has no field %q; it has %v", className, field, class.order)
					continue
				}
				if got != decl {
					t.Errorf("%s declares\n\t%s\nwant\n\t%s", className, got, decl)
				}
			}
		})
	}

	// The input classes must have NO field beyond those listed: an untagged
	// field added later would appear here under its Go name, which is the exact
	// defect this ticket fixed.
	for _, className := range []string{"service.NewNode", "service.SearchOptions"} {
		t.Run(className+" has no other field", func(t *testing.T) {
			for _, field := range classes[className].order {
				if _, expected := want[className][field]; !expected {
					t.Errorf("%s has the unexpected field %q — is it missing a json tag?",
						className, classes[className].fields[field])
				}
			}
		})
	}
}

// models.ts declares no class for domain.Date.
//
// A Date crosses as the string "2026-10-02" and never as an object, so a class
// describing {Year, Month, Day} is a type that documents a shape nothing sends —
// and one an autocomplete would offer to whoever writes the store next. It was
// emitted because Wails registers every struct it can reach by reflection; the
// empty json tags on domain.Date's fields are what stop it, and the reasoning is
// on the type.
func TestGeneratedModelsHaveNoDateClass(t *testing.T) {
	src := readGenerated(t, "models.ts")

	for name := range parseModels(t, src) {
		if name == "domain.Date" {
			t.Errorf("models.ts declares %s again. A date is a string on the wire; see the doc on domain.Date "+
				"for why its fields carry an empty json tag, and do not change it to json:\"-\"", name)
		}
	}
	for _, member := range []string{"Year: number", "Month: number", "Day: number"} {
		if strings.Contains(src, member) {
			t.Errorf("models.ts contains %q: a calendar date is leaking as its components", member)
		}
	}
}

// Nothing in the generated client refers to a type the generated client does not
// declare.
//
// This is how MoveToColumn's `target domain.Status` was caught. Wails writes a
// named Go type straight into App.d.ts — `arg2: domain.Status` — but only emits
// a TypeScript declaration for a type registered with EnumBind, so the client
// did not compile: "Namespace 'domain' has no exported member 'Status'". Gate 4
// could not see it, because tsconfig includes src/ only and nothing in src/
// imports the client yet; S2-13 is the ticket that would have hit it.
//
// A parameter is a string now, which is what a status is on the wire. This test
// is the general form of that fix, so the next bound method taking a named type
// fails here instead of in the frontend.
func TestGeneratedClientReferencesNothingUndeclared(t *testing.T) {
	models := readGenerated(t, "models.ts")
	declared := parseModels(t, models)

	for _, file := range []string{"models.ts", "main/App.d.ts"} {
		t.Run(file, func(t *testing.T) {
			for _, m := range tsRefRe.FindAllStringSubmatch(readGenerated(t, file), -1) {
				ref := m[1] + "." + m[2]
				if _, ok := declared[ref]; !ok {
					t.Errorf("%s refers to %s, which models.ts does not declare. "+
						"Wails writes a named Go type into the client verbatim and only "+
						"generates a declaration for a struct or a bound enum — so the "+
						"generated TypeScript does not compile. Cross that value as the "+
						"string it is on the wire.", file, ref)
				}
			}
		})
	}
}

// No generated field is left as `any`.
//
// `// Go type: time` above an `any` is the generator saying it did not know what
// to write. It is not a wrong shape, but it is not a description either, and a
// frontend that is required to compute nothing needs a type it can actually
// hold to.
func TestGeneratedModelsLeaveNoFieldUntyped(t *testing.T) {
	for i, line := range strings.Split(readGenerated(t, "models.ts"), "\n") {
		if strings.Contains(line, "// Go type:") {
			t.Errorf("models.ts:%d: %s — the field below it generated as `any`; tag it ts_type",
				i+1, strings.TrimSpace(line))
		}
	}
}

func classNames(classes map[string]tsClass) []string {
	names := make([]string, 0, len(classes))
	for name := range classes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
