// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {domain} from '../models';

export function ArchiveNode(arg1:string):Promise<number>;

export function Board():Promise<Array<service.ColumnView>>;

export function CheckHabit(arg1:string,arg2:string):Promise<Array<service.HabitView>>;

export function CreateNode(arg1:service.NewNode):Promise<domain.Node>;

export function HabitStrip():Promise<Array<service.HabitView>>;

export function MoveNode(arg1:string,arg2:string,arg3:number):Promise<domain.Node>;

export function MoveToColumn(arg1:string,arg2:domain.Status):Promise<domain.Node>;

export function Progress(arg1:string):Promise<service.ProgressView>;

export function RestoreNode(arg1:string):Promise<number>;

export function Search(arg1:string,arg2:service.SearchOptions):Promise<Array<service.NodeView>>;

export function SetAccent(arg1:string):Promise<service.SettingsView>;

export function SetDue(arg1:string,arg2:string):Promise<domain.Node>;

export function SetLanguage(arg1:string):Promise<service.SettingsView>;

export function SetPalette(arg1:string):Promise<service.SettingsView>;

export function SetTheme(arg1:string):Promise<service.SettingsView>;

export function Settings():Promise<service.SettingsView>;

export function TimerCurrent():Promise<service.TimerView>;

export function TimerStart(arg1:string):Promise<service.TimerView>;

export function TimerStop():Promise<service.TimerView>;

export function Tree(arg1:string):Promise<Array<service.NodeView>>;

export function UncheckHabit(arg1:string,arg2:string):Promise<Array<service.HabitView>>;
