// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveNode(arg1) {
  return window['go']['main']['App']['ArchiveNode'](arg1);
}

export function Board() {
  return window['go']['main']['App']['Board']();
}

export function CheckHabit(arg1, arg2) {
  return window['go']['main']['App']['CheckHabit'](arg1, arg2);
}

export function CreateNode(arg1) {
  return window['go']['main']['App']['CreateNode'](arg1);
}

export function HabitStrip() {
  return window['go']['main']['App']['HabitStrip']();
}

export function MoveNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveNode'](arg1, arg2, arg3);
}

export function MoveToColumn(arg1, arg2) {
  return window['go']['main']['App']['MoveToColumn'](arg1, arg2);
}

export function Progress(arg1) {
  return window['go']['main']['App']['Progress'](arg1);
}

export function RestoreNode(arg1) {
  return window['go']['main']['App']['RestoreNode'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SetAccent(arg1) {
  return window['go']['main']['App']['SetAccent'](arg1);
}

export function SetDue(arg1, arg2) {
  return window['go']['main']['App']['SetDue'](arg1, arg2);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetPalette(arg1) {
  return window['go']['main']['App']['SetPalette'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function TimerCurrent() {
  return window['go']['main']['App']['TimerCurrent']();
}

export function TimerStart(arg1) {
  return window['go']['main']['App']['TimerStart'](arg1);
}

export function TimerStop() {
  return window['go']['main']['App']['TimerStop']();
}

export function Tree(arg1) {
  return window['go']['main']['App']['Tree'](arg1);
}

export function UncheckHabit(arg1, arg2) {
  return window['go']['main']['App']['UncheckHabit'](arg1, arg2);
}
